### ISSUE TITLE
extra permission needed for running in Application mode

### ISSUE THREAD

**Issue by eoq** [goodworkaround/blogscripts#1]
Nice script. Very helpful.

I found that when running with Application permissions (vs Delegated), I had to add the permission 'Policy.Read.All' otherwise I would get the error:

Caught error when getting named locations: {"error":{"code":"AccessDenied","message":"You cannot perform the requested operation, required scopes are missing in the token."

I found other references if this issue when working with Policies and MS Graph.

You may want to add that to the README in case it helps the next person.

Thanks,
Ed

**Comment by mariussm** [comment]
Thanks, fixed
